### ISSUE TITLE
split text_map.json file into individual languages

### ISSUE THREAD

**Issue by bd-charu** [seriaati/enka-py-assets#1]
please update it so that only the needed language is loaded when initiating the client. thanks

**Comment by seriaati** [comment]
noted

**Comment by seriaati** [comment]
Done, the latest enka-py git version should be compatible with this new version of enka-py-assets, please help me test a bit on your end, thanks.

**Comment by bd-charu** [comment]
okay I will test them now, I will report here if I encounter any issues. thanks again

**Comment by bd-charu** [comment]
no issues encountered so far. I'm closing this ticket now.
